
server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/m4saosw/floricultura-microservices-config-repo/
          search-paths: fornecedor-api, loja-api, transportador-api
